[package]
name = "cardsharp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
rand = "0.9.2"
serde.features = ["derive"]
serde.version = "1.0.219"
serde_json = "1.0.143"
toml = "0.9.5"
