[package]
name = "cardsharp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
base64 = "0.22.1"
clap = { version = "4.5.47", features = ["derive"] }
crossterm = "0.29.0"
rand = "0.9.2"
rusqlite = "0.37.0"
